namespace ResourceInformationV2.Data.PageList {

    public static class PageGroup {

        private static readonly Dictionary<SidebarEnum, List<PageLink>> _breadcrumbs = new() {
            { SidebarEnum.Configuration, new() { new ("Home", "/"),
                                 new ("Configuration", "/configuration/sources") } },
            { SidebarEnum.ConfigurationNoSource, new() { new ("Home", "/"),
                                 new ("Configuration", "/configuration/sources") } },
            { SidebarEnum.Instructions, new() { new ("Home", "/"),
                                 new ("Configuration", "/configuration/sources"),
                                 new ("Options and Instructions", "/configuration/instructions/resources") } },
            { SidebarEnum.Transfer, new() { new ("Home", "/"),
                                 new ("Transfer", "/transfer/general") } },
            { SidebarEnum.Review, new() { new ("Home", "/"),
                                 new ("Review", "/review/general") } },
            { SidebarEnum.AddEditInformation, new() { new ("Home", "/"),
                                 new ("Add/Edit Information", "/add") } },
            { SidebarEnum.PeopleItem, new() { new ("Home", "/"),
                                 new ("Edit", "/edit"),
                                 new ("People", "/person/general") } },
            { SidebarEnum.PublicationItem, new() { new ("Home", "/"),
                                 new ("Edit", "/edit"),
                                 new ("Publications", "/publication/general") } },
            { SidebarEnum.ResourceItem, new() { new ("Home", "/"),
                        new ("Edit", "/edit"),
                        new ("Resources", "/resource/general") } },
            { SidebarEnum.FaqItem, new() { new ("Home", "/"),
                        new ("Edit", "/edit"),
                        new ("FAQs", "/faq/general") } },
            { SidebarEnum.NotesItem, new() { new ("Home", "/"),
                        new ("Edit", "/edit"),
                        new ("Notes", "/note/general") } },
            { SidebarEnum.EventItem, new() { new ("Home", "/"),
                        new ("Edit", "/edit"),
                        new ("Notes", "/event/general") } }
        };

        private static readonly Dictionary<SidebarEnum, List<PageLink>> _sidebars = new() {
            { SidebarEnum.None, [] },
            { SidebarEnum.AddEditInformation, new() { new ("Add Information", "/add"),
                                     new ("Edit Information", "/edit") } },
            { SidebarEnum.ResourceItem, new() { new ("General Information", "/resource/general"),
                                 new ("Image and Video", "/resource/image"),
                                 new ("Filters", "/resource/filters"),
                                 new ("Related Links", "/resource/relatedlinks"),
                                 new ("Technical Information", "/resource/technical") } },
            { SidebarEnum.PublicationItem, new() { new ("General Information", "/publication/general"),
                                 new ("Publication Detail", "/publication/detail"),
                                 new ("Image and Video", "/publication/image"),
                                 new ("Filters", "/publication/filters"),
                                 new ("Related Links", "/publication/relatedlinks"),
                                 new ("Technical Information", "/publication/technical") } },
            { SidebarEnum.PeopleItem, new() { new ("General Information", "/person/general"),
                                 new ("Image and Video", "/person/image"),
                                 new ("Filters", "/person/filters"),
                                 new ("Related Links", "/person/relatedlinks"),
                                 new ("Technical Information", "/person/technical") } },
            { SidebarEnum.FaqItem, new() { new ("General Information", "/faq/general"),
                                 new ("Rich Text", "/faq/detail"),
                                 new ("Image and Video", "/faq/image"),
                                 new ("Filters", "/faq/filters"),
                                 new ("Related Links", "/faq/relatedlinks"),
                                 new ("Technical Information", "/faq/technical") } },
            { SidebarEnum.NotesItem, new() { new ("General Information", "/note/general"),
                                 new ("Rich Text", "/note/detail"),
                                 new ("Image and Video", "/note/image"),
                                 new ("Filters", "/note/filters"),
                                 new ("Related Links", "/note/relatedlinks"),
                                 new ("Technical Information", "/note/technical") } },
            { SidebarEnum.EventItem, new() { new ("General Information", "/event/general"),
                                 new ("Event Detail", "/event/detail"),
                                 new ("Image and Video", "/event/image"),
                                 new ("Filters", "/event/filters"),
                                 new ("Related Links", "/event/relatedlinks"),
                                 new ("Technical Information", "/event/technical") } },
            { SidebarEnum.Review, new() { new ("View Drafts", "/viewdrafts"),
                                 new ("Review", "/review"),
                                 new ("Edit Review Process", "/editreview") } },
            { SidebarEnum.Transfer, new() { new ("Load Tab-Delimited File to the Server", "/transfer/load"),
                                 new ("Save Information to Tab-Delimited File", "/transfer/save"),
                                 new ("Load JSON Information to the Server", "/transfer/loadjson"),
                                 new ("Save Information to JSON", "/transfer/savejson")} },
            { SidebarEnum.Instructions, new() { new ("Resources", "/configuration/instructions/resources"),
                                 new ("Publications", "/configuration/instructions/publications"),
                                 new ("People", "/configuration/instructions/people"),
                                 new ("Events", "/configuration/instructions/events"),
                                 new ("FAQs", "/configuration/instructions/faqs"),
                                 new ("Notes", "/configuration/instructions/notes") } },
            { SidebarEnum.Configuration, new() { new ("Sources", "/configuration/sources"),
                                 new ("Options and Instructions", "/configuration/instructions/resources"),
                                 new ("Manage Filters", "/configuration/filters"),
                                 new ("Security", "/configuration/security"),
                                 new ("Request Deletion", "/configuration/requestdeletion"),
                                 new ("Testing Access", "/configuration/testing") } },
            { SidebarEnum.ConfigurationNoSource, new() { new ("Sources", "/configuration/sources"),
                                 new ("Testing Access", "/configuration/testing") } },
        };

        public static List<PageLink>? GetBreadcrumbs(SidebarEnum s) => _breadcrumbs.TryGetValue(s, out var value) ? value : null;

        public static List<PageLink>? GetSidebar(SidebarEnum s) => _sidebars.TryGetValue(s, out var value) ? [.. value] : null;
    }
}